name: development

on:
  push:
    branches-ignore: [ main ]

env:
  NUSHELL_VERSION: 0.88.0

jobs:
  build:
    name: pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set-up-go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.5

      - name: set up nushell
        uses: hustcer/setup-nu@v3.8
        with:
          version: ${{ env.NUSHELL_VERSION }}

      - name: provision
        run: make provision

      - name: check
        run: make check

      - name: build
        run: make simple-build

      - name: test
        run: make test

      - name: get version
        run: |
          ./bin/sbot update version --debug
          ./bin/sbot get version --debug
