name: development

on:
  push:
    branches-ignore: [ main ]

env:
  GO_VERSION: 1.21
  NUSHELL_VERSION: 0.91.0

jobs:
  build:
    name: pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: go.sum
          go-version: ${{ env.GO_VERSION }}

      - name: set up nushell
        uses: hustcer/setup-nu@v3.8
        with:
          version: ${{ env.NUSHELL_VERSION }}

      - name: set up path
        run: |
          mkdir bin
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: provision
        run: make provision

      - name: check
        run: make check

      - name: test
        run: make test

      - name: build prerelease
        run: |
          nu main.nu build
          sbot version
          sbot update version --debug

      - name: build
        run: |
          nu main.nu build --all --version "$(sbot predict version --debug)"
          cp bin/sbot-linux-amd64 bin/sbot
          sbot version
